<a href="https://colab.research.google.com/github/Quinntes/Bootcamp/blob/main/Portofolio_Modul_2_Uriel_Lutfhi_Hezkiel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Library

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Read CSV File dari Google Drive

In [ ]:
# Read sheet 1 untuk df_penjualan
sheet_url1 = 'https://docs.google.com/spreadsheets/d/149hwQ5H3xoFJbe3yht5luup9SM-wzzam/edit?gid=1345765640#gid=1345765640'

sheet_url_csv = sheet_url1.replace('/edit?gid=', '/export?format=csv&gid=').replace('/edit#gid=', '/export?format=csv&gid=')

df_penjualan = pd.read_csv(sheet_url_csv)

# Read sheet 2 untuk df_pelanggan

sheet_url2 = 'https://docs.google.com/spreadsheets/d/149hwQ5H3xoFJbe3yht5luup9SM-wzzam/edit?gid=1604330357#gid=1604330357'
sheet_url_csv2 = sheet_url2.replace('/edit?gid=', '/export?format=csv&gid=').replace('/edit#gid=', '/export?format=csv&gid=')

df_pelanggan = pd.read_csv(sheet_url_csv2)

# Read sheet 3 untuk df_produk

sheet_url3 = 'https://docs.google.com/spreadsheets/d/149hwQ5H3xoFJbe3yht5luup9SM-wzzam/edit?gid=1648906654#gid=1648906654'
sheet_url_csv3 = sheet_url3.replace('/edit?gid=', '/export?format=csv&gid=').replace('/edit#gid=', '/export?format=csv&gid=')

df_produk = pd.read_csv(sheet_url_csv3)

# Cek info DF

In [ ]:
df_penjualan.info()
df_pelanggan.info()
df_produk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9022 entries, 0 to 9021
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   no_bon          8862 non-null   object
 1   id_pelanggan    8864 non-null   object
 2   tanggal_bon     9016 non-null   object
 3   kota            8872 non-null   object
 4   id_produk       8868 non-null   object
 5   jumlah_terjual  9022 non-null   int64
 6   diskon          9022 non-null   int64
 7   rating          9022 non-null   int64
 8   Komplain        9022 non-null   object
dtypes: int64(3), object(6)
memory usage: 634.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_pelanggan    2000 non-null   object
 1   nama_pelanggan  2000 non-null   object
 2   gender          2000 non-null   object
 3   tanggal_lahir   2000 non-null   object
dtypes: object(4)
memory usage: 62.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_produk     74 non-null     object
 1   jenis_barang  74 non-null     object
 2   merek_barang  74 non-null     object
 3   harga_satuan  74 non-null     int64
 4   modal         74 non-null     int64
dtypes: int64(2), object(3)
memory usage: 3.0+ KB

# Join 3 DF menjadi 1 DF

1. Cek Kolom semua DF
2. Pilih kolom yang sama antar DF agar bisa di join:

- df_penjualan(id_pelanggan) = df_pelanggan(id_pelanggan)

- df_penjualan(id_produk) = df_produk(id_produk)

In [ ]:
# join df_penjualan(id_pelanggan) = df_pelanggan(id_pelanggan)

df_join1 = df_penjualan.merge(df_pelanggan, on='id_pelanggan', how='left')

In [ ]:
# df_penjualan(id_produk) = df_produk(id_produk)

df = df_join1.merge(df_produk, on='id_produk', how='left')

In [ ]:
# Cek tipe data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9022 entries, 0 to 9021
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   no_bon          8862 non-null   object
 1   id_pelanggan    8864 non-null   object
 2   tanggal_bon     9016 non-null   object
 3   kota            8872 non-null   object
 4   id_produk       8868 non-null   object
 5   jumlah_terjual  9022 non-null   int64
 6   diskon          9022 non-null   int64
 7   rating          9022 non-null   int64
 8   Komplain        9022 non-null   object
 9   nama_pelanggan  8864 non-null   object
 10  gender          8864 non-null   object
 11  tanggal_lahir   8864 non-null   object
 12  jenis_barang    8868 non-null   object
 13  merek_barang    8868 non-null   object
 14  harga_satuan    8868 non-null   float64
 15  modal           8868 non-null   float64
dtypes: float64(2), int64(3), object(11)
memory usage: 1.1+ MB

# Cleaning

## Cek duplikat berdasarkan no_bon (unique key)

In [ ]:
# copy df ke df_dc agar ada backup
df_dc = df.copy()

In [ ]:
# buat df baru untuk cek no_bon duplikat

df_non_null = df_dc[df_dc['no_bon'].notnull()]
df_duplikat_semua = df_non_null[df_non_null['no_bon'].duplicated(keep=False)]
df_duplikat_semua

,no_bon,id_pelanggan,tanggal_bon,kota,id_produk,jumlah_terjual,diskon,rating,Komplain,nama_pelanggan,gender,tanggal_lahir,jenis_barang,merek_barang,harga_satuan,modal
374,BON04317,PEL01775,3/7/2021,Jakarta,PRD00042,13,0,1,yes,Sari APB,P,2/17/1977,Speaker,Robot,1500000.0,1241712.0
379,BON04317,PEL01775,3/7/2021,Jakarta,PRD00042,13,0,2,no,Sari APB,P,2/17/1977,Speaker,Robot,1500000.0,1241712.0
1709,BON01818,PEL00792,10/27/2021,Bogor,PRD00025,13,0,1,yes,Budi WQS,L,6/24/1983,Keyboard,Panasonic,400000.0,287728.0
1714,BON01818,PEL00792,10/27/2021,Bogor,PRD00025,13,0,5,no,Budi WQS,L,6/24/1983,Keyboard,Panasonic,400000.0,287728.0
2042,BON04188,PEL01506,12/25/2021,Jakarta,PRD00029,77,25,3,no,Agus WFE,L,4/13/1994,Printer,Brother,900000.0,607976.0
2045,BON04188,PEL01506,12/25/2021,Jakarta,PRD00029,77,25,2,no,Agus WFE,L,4/13/1994,Printer,Brother,900000.0,607976.0
2237,BON03432,PEL01771,2/3/2022,Bandung,PRD00025,17,15,3,no,Tina EVC,P,10/14/1984,Keyboard,Panasonic,400000.0,287728.0
2243,BON03432,PEL01771,2/3/2022,Bandung,PRD00025,17,15,2,no,Tina EVC,P,10/14/1984,Keyboard,Panasonic,400000.0,287728.0
2442,BON08719,PEL01544,3/11/2022,Depok,PRD00004,17,10,1,yes,Budi NPI,L,1/6/2002,Mouse,Corsair,425000.0,267954.0
2444,BON08719,PEL01544,3/11/2022,Depok,PRD00004,17,10,1,yes,Budi NPI,L,1/6/2002,Mouse,Corsair,425000.0,267954.0
4944,BON01812,PEL01815,6/11/2023,Depok,PRD00020,29,15,4,no,Agus CXV,L,12/8/1975,Keyboard,Samsung,600000.0,501505.0
4953,BON01812,PEL01815,6/11/2023,Depok,PRD00020,29,15,1,yes,Agus CXV,L,12/8/1975,Keyboard,Samsung,600000.0,501505.0
5117,BON07363,PEL00362,7/15/2023,Jakarta,PRD00015,30,0,4,no,Agus QEK,L,7/20/1992,Monitor,ViewSonic,1950000.0,1227395.0
5119,BON07363,PEL00362,7/15/2023,Jakarta,PRD00015,30,0,5,no,Agus QEK,L,7/20/1992,Monitor,ViewSonic,1950000.0,1227395.0
7180,BON04253,PEL01943,7/19/2024,Jakarta,PRD00067,27,0,4,no,Lia JIZ,P,6/4/1999,PC Rakitan,MJ013,24000000.0,20554678.0
7182,BON04253,PEL01943,7/19/2024,Jakarta,PRD00067,27,0,1,yes,Lia JIZ,P,6/4/1999,PC Rakitan,MJ013,24000000.0,20554678.0

In [ ]:
# no_bon sebagai unique key, drop duplikat no_bon yang ratingnya lebih tinggi

df_dc = df_dc.sort_values(by=['no_bon', 'rating'], ascending=[True, True]) #
df_dc = df_dc.drop_duplicates(subset='no_bon', keep='first')